/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiLeadRouteImport } from './routes/api/lead'
import { Route as ApiMeetingRouteImport } from './routes/api/meeting'
import { Route as ApiProjectsRouteImport } from './routes/api/projects'
import { Route as ApiAuthGoogleLeadRouteImport } from './routes/api/auth/google-lead'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeetingRoute = ApiMeetingRouteImport.update({
  id: '/api/meeting',
  path: '/api/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProjectsRoute = ApiProjectsRouteImport.update({
  id: '/api/projects',
  path: '/api/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleLeadRoute = ApiAuthGoogleLeadRouteImport.update({
  id: '/api/auth/google-lead',
  path: '/api/auth/google-lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/meeting': typeof ApiMeetingRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/auth/google-lead': typeof ApiAuthGoogleLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/meeting': typeof ApiMeetingRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/auth/google-lead': typeof ApiAuthGoogleLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/api/contact': typeof ApiContactRoute
  '/api/lead': typeof ApiLeadRoute
  '/api/meeting': typeof ApiMeetingRoute
  '/api/projects': typeof ApiProjectsRoute
  '/api/auth/google-lead': typeof ApiAuthGoogleLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/contact'
    | '/api/lead'
    | '/api/meeting'
    | '/api/projects'
    | '/api/auth/google-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/contact'
    | '/api/lead'
    | '/api/meeting'
    | '/api/projects'
    | '/api/auth/google-lead'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/api/contact'
    | '/api/lead'
    | '/api/meeting'
    | '/api/projects'
    | '/api/auth/google-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiLeadRoute: typeof ApiLeadRoute
  ApiMeetingRoute: typeof ApiMeetingRoute
  ApiProjectsRoute: typeof ApiProjectsRoute
  ApiAuthGoogleLeadRoute: typeof ApiAuthGoogleLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meeting': {
      id: '/api/meeting'
      path: '/api/meeting'
      fullPath: '/api/meeting'
      preLoaderRoute: typeof ApiMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/projects': {
      id: '/api/projects'
      path: '/api/projects'
      fullPath: '/api/projects'
      preLoaderRoute: typeof ApiProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google-lead': {
      id: '/api/auth/google-lead'
      path: '/api/auth/google-lead'
      fullPath: '/api/auth/google-lead'
      preLoaderRoute: typeof ApiAuthGoogleLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ApiContactRoute: ApiContactRoute,
  ApiLeadRoute: ApiLeadRoute,
  ApiMeetingRoute: ApiMeetingRoute,
  ApiProjectsRoute: ApiProjectsRoute,
  ApiAuthGoogleLeadRoute: ApiAuthGoogleLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
